import type { RouteDefinition } from "../lib/http/router";
import {
	handleActivateInvite,
	handleForgotPassword,
	handleGetMe,
	handlePreviewInvite,
	handlePreviewPasswordReset,
	handleRegenerateIntendantPassword,
	handleResetPassword,
	handleSignIn,
	handleSignOut,
	handleUpdateMe,
} from "../controllers/auth";
import {
	handleConfirmMfa,
	handleDisableMfa,
	handleGetMfaStatus,
	handleSendMfaDisableRecoveryCode,
	handleSetupMfa,
	handleVerifyMfaSignIn,
} from "../controllers/mfa";
import {
	handleSendRecoveryEmailCode,
	handleVerifyRecoveryEmail,
} from "../controllers/recovery-email";
import {
	handleListSessions,
	handleRevokeAllSessions,
	handleRevokeSession,
} from "../controllers/sessions";
import {
	handleAssignRole,
	handleCreatePasswordResetCode,
	handleDisableAccountMfa,
	handleGetAccount,
	handleGetAccountMfaStatus,
	handleGetDomainLocalPartPolicy,
	handleGrantSharedMailboxAccess,
	handleGrantManagerMailboxAssignment,
	handleInviteAccount,
	handleListAccounts,
	handleListAccountSessions,
	handleListMailboxGrantHolders,
	handleListMailboxManagerAssignments,
	handleRegenerateInviteCode,
	handleRemoveAccount,
	handleRevokeAccountSession,
	handleRevokeAllAccountSessions,
	handleRevokeSharedMailboxAccess,
	handleRevokeManagerMailboxAssignment,
	handleSuggestInviteLocalPart,
	handleSuspendAccount,
	handleUnsuspendAccount,
	handleUpdateAccount,
	handleUpdateAccountAssignments,
	handleUpdateDomainLocalPartPolicy,
} from "../controllers/accounts";
import { handleListAccountIdentitiesForAccount } from "../controllers/identities";
import {
	handleCreateApiKey,
	handleListApiKeys,
	handleRevokeApiKey,
} from "../controllers/api-keys";
import {
	handleAdminRevokeOidcClientGrant,
	handleCreateOidcClient,
	handleDeleteOidcClient,
	handleDeleteOidcClientLogo,
	handleGetOidcClient,
	handleGetOidcClientLogo,
	handleGetOidcPending,
	handleListMyOidcGrants,
	handleListOidcClientGrants,
	handleListOidcClients,
	handleOidcAuthorize,
	handleOidcConsentDecision,
	handleOidcJwks,
	handleOidcToken,
	handleOidcUserinfo,
	handleOpenIdDiscovery,
	handleRegenerateOidcClientSecret,
	handleRevokeMyOidcGrant,
	handleUpdateOidcClient,
	handleUploadOidcClientLogo,
} from "../controllers/oidc";
import {
	handleGetInstanceSettings,
	handleUpdateInstanceSettings,
} from "../controllers/instance-settings";
import { handleListLogs } from "../controllers/logs";
import {
	handleDeleteProfilePicture,
	handleDeleteAccountProfilePicture,
	handleGetProfilePicture,
	handleUploadAccountProfilePicture,
	handleUploadProfilePicture,
} from "../controllers/profile-picture";
import {
	handleBeginPasskeyRegistration,
	handleBeginPasskeySignIn,
	handleCompletePasskeyRegistration,
	handleCompletePasskeySignIn,
	handleListPasskeys,
	handleRemovePasskey,
} from "../controllers/passkeys";

const prefix = "/api/v1";

export const authRoutes: RouteDefinition[] = [
	{
		method: "POST",
		path: `${prefix}/auth/sign-in`,
		auth: false,
		authRateLimit: { keyFields: ["email"] },
		handler: handleSignIn,
	},
	{
		method: "POST",
		path: `${prefix}/auth/passkeys/sign-in/options`,
		auth: false,
		authRateLimit: { keyFields: ["email"] },
		handler: handleBeginPasskeySignIn,
	},
	{
		method: "POST",
		path: `${prefix}/auth/passkeys/sign-in/verify`,
		auth: false,
		authRateLimit: { keyFields: ["email"] },
		handler: handleCompletePasskeySignIn,
	},
	{ method: "GET", path: `${prefix}/auth/passkeys`, action: "authenticated", handler: handleListPasskeys },
	{
		method: "POST",
		path: `${prefix}/auth/passkeys/register/options`,
		action: "authenticated",
		handler: handleBeginPasskeyRegistration,
	},
	{
		method: "POST",
		path: `${prefix}/auth/passkeys/register/verify`,
		action: "authenticated",
		handler: handleCompletePasskeyRegistration,
	},
	{
		method: "DELETE",
		path: `${prefix}/auth/passkeys/:id`,
		action: "authenticated",
		handler: handleRemovePasskey,
	},
	{ method: "POST", path: `${prefix}/auth/sign-out`, auth: false, handler: handleSignOut },
	{
		method: "POST",
		path: `${prefix}/auth/mfa/verify`,
		auth: false,
		authRateLimit: { keyFields: ["mfaToken"] },
		handler: handleVerifyMfaSignIn,
	},
	{ method: "GET", path: `${prefix}/auth/mfa`, action: "authenticated", handler: handleGetMfaStatus },
	{ method: "POST", path: `${prefix}/auth/mfa/setup`, action: "authenticated", handler: handleSetupMfa },
	{ method: "POST", path: `${prefix}/auth/mfa/confirm`, action: "authenticated", handler: handleConfirmMfa },
	{
		method: "POST",
		path: `${prefix}/auth/mfa/disable/send-recovery-code`,
		action: "authenticated",
		handler: handleSendMfaDisableRecoveryCode,
	},
	{ method: "DELETE", path: `${prefix}/auth/mfa`, action: "authenticated", handler: handleDisableMfa },
	{
		method: "POST",
		path: `${prefix}/auth/activate`,
		auth: false,
		authRateLimit: { keyFields: ["code"] },
		handler: handleActivateInvite,
	},
	{
		method: "GET",
		path: `${prefix}/auth/invite-preview`,
		auth: false,
		authRateLimit: { keyFields: ["code"] },
		handler: handlePreviewInvite,
	},
	{
		method: "GET",
		path: `${prefix}/auth/reset-preview`,
		auth: false,
		authRateLimit: { keyFields: ["code"] },
		handler: handlePreviewPasswordReset,
	},
	{
		method: "POST",
		path: `${prefix}/auth/forgot-password`,
		auth: false,
		authRateLimit: { keyFields: ["address"] },
		handler: handleForgotPassword,
	},
	{
		method: "POST",
		path: `${prefix}/auth/reset-password`,
		auth: false,
		authRateLimit: { keyFields: ["code"] },
		handler: handleResetPassword,
	},
	{
		method: "GET",
		path: `${prefix}/auth/me`,
		action: "authenticated",
		scopes: ["profile:read"],
		handler: handleGetMe,
	},
	{
		method: "PATCH",
		path: `${prefix}/auth/me`,
		action: "authenticated",
		scopes: ["profile:update"],
		handler: handleUpdateMe,
	},
	{
		method: "PUT",
		path: `${prefix}/auth/me/profile-picture`,
		action: "authenticated",
		scopes: ["profile_picture:update"],
		handler: handleUploadProfilePicture,
	},
	{
		method: "DELETE",
		path: `${prefix}/auth/me/profile-picture`,
		action: "authenticated",
		scopes: ["profile_picture:delete"],
		handler: handleDeleteProfilePicture,
	},
	{
		method: "GET",
		path: `${prefix}/accounts/:id/profile-picture`,
		auth: false,
		handler: handleGetProfilePicture,
	},
	{
		method: "PUT",
		path: `${prefix}/accounts/:id/profile-picture`,
		action: "domain_manage_users",
		scopes: ["account_profile_pictures:update"],
		handler: handleUploadAccountProfilePicture,
	},
	{
		method: "DELETE",
		path: `${prefix}/accounts/:id/profile-picture`,
		action: "domain_manage_users",
		scopes: ["account_profile_pictures:delete"],
		handler: handleDeleteAccountProfilePicture,
	},
	{
		method: "POST",
		path: `${prefix}/auth/recovery-email/send`,
		action: "authenticated",
		handler: handleSendRecoveryEmailCode,
	},
	{
		method: "POST",
		path: `${prefix}/auth/recovery-email/verify`,
		action: "authenticated",
		handler: handleVerifyRecoveryEmail,
	},
	{ method: "GET", path: `${prefix}/auth/sessions`, action: "authenticated", handler: handleListSessions },
	{
		method: "DELETE",
		path: `${prefix}/auth/sessions/:id`,
		action: "authenticated",
		handler: handleRevokeSession,
	},
	{
		method: "DELETE",
		path: `${prefix}/auth/sessions`,
		action: "authenticated",
		handler: handleRevokeAllSessions,
	},
	{
		method: "POST",
		path: `${prefix}/auth/intendant/regenerate-password`,
		action: "platform",
		handler: handleRegenerateIntendantPassword,
	},

	{
		method: "GET",
		path: `${prefix}/accounts`,
		action: "domain_manage_users",
		scopes: ["accounts:list"],
		handler: handleListAccounts,
	},
	{
		method: "GET",
		path: `${prefix}/accounts/:id`,
		action: "domain_manage_users",
		scopes: ["accounts:read"],
		handler: handleGetAccount,
	},
	{
		method: "GET",
		path: `${prefix}/accounts/:id/identities`,
		action: "domain_manage_users",
		scopes: ["accounts:read", "identities:list"],
		handler: handleListAccountIdentitiesForAccount,
	},
	{
		method: "PATCH",
		path: `${prefix}/accounts/:id`,
		action: "domain_manage_users",
		scopes: ["accounts:update"],
		handler: handleUpdateAccount,
	},
	{
		method: "PATCH",
		path: `${prefix}/accounts/:id/assignments`,
		action: "domain_manage_users",
		scopes: ["account_assignments:update"],
		handler: handleUpdateAccountAssignments,
	},
	{
		method: "POST",
		path: `${prefix}/accounts/invite`,
		action: "domain_manage_users",
		scopes: ["accounts:invite"],
		handler: handleInviteAccount,
	},
	{
		method: "POST",
		path: `${prefix}/accounts/invite/suggest-local-part`,
		action: "domain_manage_users",
		scopes: ["accounts:suggest_local_part"],
		handler: handleSuggestInviteLocalPart,
	},
	{
		method: "POST",
		path: `${prefix}/accounts/assign-role`,
		action: "domain_manage_users",
		scopes: ["accounts:assign_role"],
		handler: handleAssignRole,
	},
	{
		method: "POST",
		path: `${prefix}/accounts/:id/suspend`,
		action: "domain_manage_users",
		scopes: ["accounts:suspend"],
		handler: handleSuspendAccount,
	},
	{
		method: "POST",
		path: `${prefix}/accounts/:id/unsuspend`,
		action: "domain_manage_users",
		scopes: ["accounts:unsuspend"],
		handler: handleUnsuspendAccount,
	},
	{
		method: "DELETE",
		path: `${prefix}/accounts/:id`,
		action: "domain_manage_users",
		scopes: ["accounts:delete"],
		handler: handleRemoveAccount,
	},
	{
		method: "POST",
		path: `${prefix}/accounts/:id/password-reset-code`,
		action: "domain_manage_users",
		scopes: ["account_password_reset_codes:create"],
		handler: handleCreatePasswordResetCode,
	},
	{
		method: "POST",
		path: `${prefix}/accounts/:id/regenerate-invite`,
		action: "domain_manage_users",
		scopes: ["account_invites:regenerate"],
		handler: handleRegenerateInviteCode,
	},
	{
		method: "GET",
		path: `${prefix}/accounts/:id/sessions`,
		action: "domain_manage_users",
		handler: handleListAccountSessions,
	},
	{
		method: "DELETE",
		path: `${prefix}/accounts/:id/sessions/:sessionId`,
		action: "domain_manage_users",
		handler: handleRevokeAccountSession,
	},
	{
		method: "DELETE",
		path: `${prefix}/accounts/:id/sessions`,
		action: "domain_manage_users",
		handler: handleRevokeAllAccountSessions,
	},
	{
		method: "GET",
		path: `${prefix}/accounts/:id/mfa`,
		action: "domain_manage_users",
		handler: handleGetAccountMfaStatus,
	},
	{
		method: "DELETE",
		path: `${prefix}/accounts/:id/mfa`,
		action: "domain_manage_users",
		handler: handleDisableAccountMfa,
	},
	{
		method: "POST",
		path: `${prefix}/accounts/:id/mailbox-grants`,
		action: "domain_manage_users",
		scopes: ["account_mailbox_grants:create"],
		handler: handleGrantSharedMailboxAccess,
	},
	{
		method: "DELETE",
		path: `${prefix}/accounts/:id/mailbox-grants/:mailboxId`,
		action: "domain_manage_users",
		scopes: ["account_mailbox_grants:delete"],
		handler: handleRevokeSharedMailboxAccess,
	},
	{
		method: "POST",
		path: `${prefix}/accounts/:id/manager-assignments`,
		action: "domain_manage_users",
		scopes: ["account_manager_assignments:create"],
		handler: handleGrantManagerMailboxAssignment,
	},
	{
		method: "DELETE",
		path: `${prefix}/accounts/:id/manager-assignments/:mailboxId`,
		action: "domain_manage_users",
		scopes: ["account_manager_assignments:delete"],
		handler: handleRevokeManagerMailboxAssignment,
	},
	{
		method: "GET",
		path: `${prefix}/mailboxes/:mailboxId/grants`,
		action: "domain_manage_users",
		scopes: ["mailbox_grants:list"],
		handler: handleListMailboxGrantHolders,
	},
	{
		method: "GET",
		path: `${prefix}/mailboxes/:mailboxId/manager-assignments`,
		action: "domain_manage_users",
		scopes: ["mailbox_manager_assignments:list"],
		handler: handleListMailboxManagerAssignments,
	},
	{
		method: "GET",
		path: `${prefix}/domains/:domainId/local-part-policy`,
		action: "domain_manage_users",
		scopes: ["domain_local_part_policies:read"],
		handler: handleGetDomainLocalPartPolicy,
	},
	{
		method: "PATCH",
		path: `${prefix}/domains/:domainId/local-part-policy`,
		action: "domain_admin",
		scopes: ["domain_local_part_policies:update"],
		handler: handleUpdateDomainLocalPartPolicy,
	},

	{ method: "GET", path: `${prefix}/api-keys`, action: "authenticated", handler: handleListApiKeys },
	{ method: "POST", path: `${prefix}/api-keys`, action: "authenticated", handler: handleCreateApiKey },
	{ method: "DELETE", path: `${prefix}/api-keys/:id`, action: "authenticated", handler: handleRevokeApiKey },

	{
		method: "POST",
		path: `${prefix}/oidc-clients`,
		action: "platform",
		scopes: ["oidc_clients:create"],
		handler: handleCreateOidcClient,
	},
	{
		method: "GET",
		path: `${prefix}/oidc-clients`,
		action: "platform",
		scopes: ["oidc_clients:read"],
		handler: handleListOidcClients,
	},
	{
		method: "GET",
		path: `${prefix}/oidc-clients/:id`,
		action: "platform",
		scopes: ["oidc_clients:read"],
		handler: handleGetOidcClient,
	},
	{
		method: "PATCH",
		path: `${prefix}/oidc-clients/:id`,
		action: "platform",
		scopes: ["oidc_clients:update"],
		handler: handleUpdateOidcClient,
	},
	{
		method: "DELETE",
		path: `${prefix}/oidc-clients/:id`,
		action: "platform",
		scopes: ["oidc_clients:delete"],
		handler: handleDeleteOidcClient,
	},
	{
		method: "GET",
		path: `${prefix}/oidc-clients/:id/logo`,
		auth: false,
		handler: handleGetOidcClientLogo,
	},
	{
		method: "PUT",
		path: `${prefix}/oidc-clients/:id/logo`,
		action: "platform",
		scopes: ["oidc_clients:update"],
		handler: handleUploadOidcClientLogo,
	},
	{
		method: "DELETE",
		path: `${prefix}/oidc-clients/:id/logo`,
		action: "platform",
		scopes: ["oidc_clients:update"],
		handler: handleDeleteOidcClientLogo,
	},
	{
		method: "POST",
		path: `${prefix}/oidc-clients/:id/regenerate-secret`,
		action: "platform",
		scopes: ["oidc_clients:update"],
		handler: handleRegenerateOidcClientSecret,
	},
	{
		method: "GET",
		path: `${prefix}/oidc-clients/:id/grants`,
		action: "platform",
		scopes: ["oidc_clients:read"],
		handler: handleListOidcClientGrants,
	},
	{
		method: "DELETE",
		path: `${prefix}/oidc-clients/:id/grants/:accountId`,
		action: "platform",
		scopes: ["oidc_clients:update"],
		handler: handleAdminRevokeOidcClientGrant,
	},
	{
		method: "GET",
		path: `${prefix}/me/oidc-grants`,
		action: "authenticated",
		handler: handleListMyOidcGrants,
	},
	{
		method: "DELETE",
		path: `${prefix}/me/oidc-grants/:clientId`,
		action: "authenticated",
		handler: handleRevokeMyOidcGrant,
	},

	{
		method: "GET",
		path: `${prefix}/instance/settings`,
		action: "platform",
		scopes: ["instance_settings:read"],
		handler: handleGetInstanceSettings,
	},
	{
		method: "PATCH",
		path: `${prefix}/instance/settings`,
		action: "platform",
		scopes: ["instance_settings:update"],
		handler: handleUpdateInstanceSettings,
	},
	{
		method: "GET",
		path: `${prefix}/logs`,
		action: "platform",
		scopes: ["logs:list"],
		handler: handleListLogs,
	},

	{
		method: "GET",
		path: "/.well-known/openid-configuration",
		auth: false,
		handler: handleOpenIdDiscovery,
	},
	{ method: "GET", path: `${prefix}/oauth/jwks`, auth: false, handler: handleOidcJwks },
	{
		method: "GET",
		path: `${prefix}/oauth/authorize`,
		auth: false,
		handler: handleOidcAuthorize,
	},
	{
		method: "POST",
		path: `${prefix}/oauth/token`,
		auth: false,
		authRateLimit: { keyFields: ["client_id"] },
		handler: handleOidcToken,
	},
	{
		method: "GET",
		path: `${prefix}/oauth/userinfo`,
		action: "authenticated",
		handler: handleOidcUserinfo,
	},
	{
		method: "GET",
		path: `${prefix}/oauth/pending/:id`,
		action: "authenticated",
		handler: handleGetOidcPending,
	},
	{
		method: "POST",
		path: `${prefix}/oauth/consent`,
		action: "authenticated",
		handler: handleOidcConsentDecision,
	},
];
