import { and, eq } from "drizzle-orm";

import { messages } from "../../db/schema";
import { authorizeMailbox } from "../auth/access";
import { formatEmailAddress } from "../addresses";
import { extractEmailsFromHeaderValue } from "../extract-emails-from-header";
import { isBlackholeMailboxType } from "../mailbox-types";
import { loadMailboxForSend } from "../mailbox-queries";
import { onOutboundSent } from "../thread-mailbox";
import {
	buildEmailSendPayload,
	buildOutboundMimeContent,
} from "./build-outbound-mime";
import {
	completeDraftSend,
	draftSendPromoteFromDrafts,
} from "./complete-draft-send";
import { canonicalizeSentMessageId } from "./message-id";
import {
	loadDraftOutboundPayload,
	loadStoredAttachmentInputs,
	outboundAttachmentsToStoredInputs,
} from "./outbound-attachments";
import type { OutboundContext } from "./outbound-context";
import {
	emitOutboundMailingLog,
	persistDraftMessage,
	sendAndPersistNewMessage,
} from "./outbound-persist";
import { prepareOutboundMessageBody } from "./prepare-email-html";
import { sendEmail } from "./send-email";

export { persistDraftMessage, sendAndPersistNewMessage };

/**
 * Outbound pipeline entry points: new sends, drafts, and promoting an existing
 * draft row to sent. Identity resolution is injected via OutboundContext.
 */
export async function sendExistingDraft(
	ctx: OutboundContext,
	messageId: string,
) {
	const [draft] = await ctx.db
		.select()
		.from(messages)
		.where(
			and(
				eq(messages.id, messageId),
				eq(messages.direction, "outbound"),
				eq(messages.sendStatus, "draft"),
			),
		)
		.limit(1);

	if (!draft) {
		throw new Error("Draft not found");
	}

	await authorizeMailbox(ctx.db, ctx.principal, draft.actualMailboxId, "send");

	const mailbox = await loadMailboxForSend(ctx.db, draft.actualMailboxId);
	if (!mailbox) {
		throw new Error("Mailbox not found or cannot send");
	}

	const rawPayload = await loadDraftOutboundPayload(ctx.bucket, draft);
	const payload = await prepareOutboundMessageBody(rawPayload);
	const { fromName } = await ctx.resolveIdentityForSend(
		ctx.db,
		ctx.principal,
		mailbox.id,
		payload.identityId,
	);
	const fromHeader = formatEmailAddress({
		email: mailbox.address,
		name: fromName || undefined,
	});
	const storedAttachmentInputs = await loadStoredAttachmentInputs(
		ctx.db,
		ctx.bucket,
		messageId,
	);
	const attachmentInputs = [
		...storedAttachmentInputs,
		...outboundAttachmentsToStoredInputs(payload.attachments),
	];
	const now = new Date();
	const sendPayload = buildEmailSendPayload({
		from: fromHeader,
		payload,
		inReplyTo: draft.inReplyTo,
		references: draft.references,
		attachmentInputs,
		autoGenerated: isBlackholeMailboxType(mailbox.type),
	});

	const toAddress =
		extractEmailsFromHeaderValue(draft.envelopeTo)[0] ??
		draft.envelopeTo ??
		extractEmailsFromHeaderValue(draft.to)[0] ??
		draft.to;

	let result: Awaited<ReturnType<typeof sendEmail>>;
	try {
		result = await sendEmail(ctx.email, sendPayload);
	} catch (error) {
		await emitOutboundMailingLog(ctx.db, {
			success: false,
			mailboxId: mailbox.id,
			toAddress,
			threadId: draft.threadId,
			messageId: draft.id,
			actorAccountId: ctx.principal.accountId,
			logContext: ctx.logContext,
		});
		throw error;
	}
	const rfcMessageId = canonicalizeSentMessageId(result.messageId);

	const sent = await completeDraftSend({
		db: ctx.db,
		bucket: ctx.bucket,
		draft,
		rfcMessageId,
		mimeContent: buildOutboundMimeContent({
			from: fromHeader,
			payload,
			rfcMessageId,
			inReplyTo: draft.inReplyTo,
			references: draft.references,
			autoGenerated: isBlackholeMailboxType(mailbox.type),
		}),
		attachmentInputs,
		sentAt: now,
		sentByAccountId: ctx.principal.accountId,
	});

	await onOutboundSent(ctx.db, {
		threadId: sent.threadId,
		touch: {
			subject: draft.subject,
			preview: draft.preview,
			lastMessageAt: now,
			actualMailboxId: mailbox.id,
			folder: sent.id !== draft.id ? "sent" : undefined,
			promoteFromDrafts: draftSendPromoteFromDrafts(draft, sent),
			markUnread: false,
		},
		message: sent,
	});

	await emitOutboundMailingLog(ctx.db, {
		success: true,
		mailboxId: mailbox.id,
		toAddress,
		threadId: sent.threadId,
		messageId: sent.id,
		actorAccountId: ctx.principal.accountId,
		logContext: ctx.logContext,
	});

	return sent;
}
