import type { RouteDefinition } from "../../lib/http/router";
import {
	handleCreateDomain,
	handleDeleteDomain,
	handleGetDomain,
	handleListDomains,
	handleUpdateDomain,
} from "../../controllers/domains";
import {
	handleCreateValidationRun,
	handleGetValidationRun,
	handleListValidationRuns,
} from "../../controllers/domain-validation";
import {
	handleCreateMailbox,
	handleDeleteMailbox,
	handleGetMailbox,
	handleListMailboxes,
	handleUpdateMailbox,
} from "../../controllers/mailboxes";
import {
	handleCreateMailboxIdentity,
	handleDeleteMailboxIdentity,
	handleListAccountIdentities,
	handleListAvailableIdentities,
	handleListMailboxIdentities,
	handleUpdateMailboxIdentity,
} from "../../controllers/identities";
import {
	handleCreateDraft,
	handleDeleteDraft,
	handleForwardToMessage,
	handleReplyToMessage,
	handleSendDraft,
	handleSendMessage,
	handleUpdateDraft,
} from "../../controllers/messages";
import {
	handleCreateLabel,
	handleDeleteLabel,
	handleGetLabel,
	handleListLabels,
	handleUpdateLabel,
} from "../../controllers/labels";
import {
	handleDownloadAttachment,
	handleDownloadMessageExternalImage,
	handleDownloadRawMessage,
	handleGetMessage,
	handleGetMessagePreview,
	handleSearch,
} from "../../controllers/messages-read";
import {
	handleGetThread,
	handleListThreadMessages,
	handleListThreads,
	handlePatchThread,
	handleThreadAction,
} from "../../controllers/threads-read";
import {
	handleCreateEmailTemplate,
	handleDeleteEmailTemplate,
	handleGetEmailTemplate,
	handleGetEmailTemplateContent,
	handleListEmailTemplates,
	handleUpdateEmailTemplate,
} from "../../controllers/email-templates";
import {
	handleDeleteSystemEmailTemplate,
	handleGetSystemEmailTemplateContent,
	handleListSystemEmailTemplates,
	handleUploadSystemEmailTemplate,
} from "../../controllers/system-email-templates";

const prefix = "/api/v1";

export const v1Routes: RouteDefinition[] = [
	{
		method: "GET",
		path: `${prefix}/domains`,
		action: "authenticated",
		scopes: ["domains:list"],
		handler: handleListDomains,
	},
	{
		method: "POST",
		path: `${prefix}/domains`,
		action: "platform",
		scopes: ["domains:create"],
		handler: handleCreateDomain,
	},
	{
		method: "GET",
		path: `${prefix}/domains/:id`,
		action: "domain_admin",
		scopes: ["domains:read"],
		handler: handleGetDomain,
	},
	{
		method: "PATCH",
		path: `${prefix}/domains/:id`,
		action: "domain_admin",
		scopes: ["domains:update"],
		handler: handleUpdateDomain,
	},
	{
		method: "DELETE",
		path: `${prefix}/domains/:id`,
		action: "domain_admin",
		scopes: ["domains:delete"],
		handler: handleDeleteDomain,
	},
	{
		method: "GET",
		path: `${prefix}/domains/:id/validation-runs`,
		action: "domain_admin",
		scopes: ["domain_validation_runs:list"],
		handler: handleListValidationRuns,
	},
	{
		method: "POST",
		path: `${prefix}/domains/:id/validation-runs`,
		action: "domain_admin",
		scopes: ["domain_validation_runs:create"],
		handler: handleCreateValidationRun,
	},
	{
		method: "GET",
		path: `${prefix}/domains/:id/validation-runs/:runId`,
		action: "domain_admin",
		scopes: ["domain_validation_runs:read"],
		handler: handleGetValidationRun,
	},

	{
		method: "GET",
		path: `${prefix}/mailboxes`,
		action: "authenticated",
		scopes: ["mailboxes:list"],
		handler: handleListMailboxes,
	},
	{
		method: "POST",
		path: `${prefix}/mailboxes`,
		action: "domain_admin",
		scopes: ["mailboxes:create"],
		handler: handleCreateMailbox,
	},
	{
		method: "GET",
		path: `${prefix}/mailboxes/:id`,
		action: "mail_read",
		scopes: ["mailboxes:read"],
		handler: handleGetMailbox,
	},
	{
		method: "PATCH",
		path: `${prefix}/mailboxes/:id`,
		action: "authenticated",
		scopes: ["mailboxes:update"],
		handler: handleUpdateMailbox,
	},
	{
		method: "DELETE",
		path: `${prefix}/mailboxes/:id`,
		action: "domain_admin",
		scopes: ["mailboxes:delete"],
		handler: handleDeleteMailbox,
	},

	{
		method: "GET",
		path: `${prefix}/identities`,
		action: "authenticated",
		scopes: ["identities:list"],
		handler: handleListAccountIdentities,
	},
	{
		method: "GET",
		path: `${prefix}/mailboxes/:mailboxId/identities`,
		action: "mail_read",
		scopes: ["identities:list"],
		handler: handleListMailboxIdentities,
	},
	{
		method: "GET",
		path: `${prefix}/mailboxes/:mailboxId/identities/available`,
		action: "mail_read",
		scopes: ["identities:list"],
		handler: handleListAvailableIdentities,
	},
	{
		method: "POST",
		path: `${prefix}/mailboxes/:mailboxId/identities`,
		action: "authenticated",
		scopes: ["identities:create"],
		handler: handleCreateMailboxIdentity,
	},
	{
		method: "PATCH",
		path: `${prefix}/mailboxes/:mailboxId/identities/:id`,
		action: "authenticated",
		scopes: ["identities:update"],
		handler: handleUpdateMailboxIdentity,
	},
	{
		method: "DELETE",
		path: `${prefix}/mailboxes/:mailboxId/identities/:id`,
		action: "authenticated",
		scopes: ["identities:delete"],
		handler: handleDeleteMailboxIdentity,
	},

	{
		method: "GET",
		path: `${prefix}/mailboxes/:mailboxId/labels`,
		action: "mail_read",
		scopes: ["labels:list"],
		handler: handleListLabels,
	},
	{
		method: "POST",
		path: `${prefix}/mailboxes/:mailboxId/labels`,
		action: "domain_admin",
		scopes: ["labels:create"],
		handler: handleCreateLabel,
	},
	{
		method: "GET",
		path: `${prefix}/mailboxes/:mailboxId/labels/:id`,
		action: "mail_read",
		scopes: ["labels:read"],
		handler: handleGetLabel,
	},
	{
		method: "PATCH",
		path: `${prefix}/mailboxes/:mailboxId/labels/:id`,
		action: "domain_admin",
		scopes: ["labels:update"],
		handler: handleUpdateLabel,
	},
	{
		method: "DELETE",
		path: `${prefix}/mailboxes/:mailboxId/labels/:id`,
		action: "domain_admin",
		scopes: ["labels:delete"],
		handler: handleDeleteLabel,
	},

	{
		method: "GET",
		path: `${prefix}/templates`,
		action: "authenticated",
		scopes: ["templates:list"],
		handler: handleListEmailTemplates,
	},
	{
		method: "POST",
		path: `${prefix}/templates`,
		action: "authenticated",
		scopes: ["templates:create"],
		handler: handleCreateEmailTemplate,
	},
	{
		method: "GET",
		path: `${prefix}/templates/:id`,
		action: "authenticated",
		scopes: ["templates:read"],
		handler: handleGetEmailTemplate,
	},
	{
		method: "GET",
		path: `${prefix}/templates/:id/content`,
		action: "authenticated",
		scopes: ["templates:read"],
		handler: handleGetEmailTemplateContent,
	},
	{
		method: "PATCH",
		path: `${prefix}/templates/:id`,
		action: "authenticated",
		scopes: ["templates:update"],
		handler: handleUpdateEmailTemplate,
	},
	{
		method: "DELETE",
		path: `${prefix}/templates/:id`,
		action: "authenticated",
		scopes: ["templates:delete"],
		handler: handleDeleteEmailTemplate,
	},

	{
		method: "GET",
		path: `${prefix}/system-templates`,
		action: "authenticated",
		scopes: ["system_templates:list"],
		handler: handleListSystemEmailTemplates,
	},
	{
		method: "PUT",
		path: `${prefix}/system-templates/:key`,
		action: "authenticated",
		scopes: ["system_templates:update"],
		handler: handleUploadSystemEmailTemplate,
	},
	{
		method: "GET",
		path: `${prefix}/system-templates/:key/content`,
		action: "authenticated",
		scopes: ["system_templates:read"],
		handler: handleGetSystemEmailTemplateContent,
	},
	{
		method: "DELETE",
		path: `${prefix}/system-templates/:key`,
		action: "authenticated",
		scopes: ["system_templates:delete"],
		handler: handleDeleteSystemEmailTemplate,
	},

	{
		method: "POST",
		path: `${prefix}/messages/send`,
		action: "mail_write",
		scopes: ["messages:send"],
		handler: handleSendMessage,
	},
	{
		method: "POST",
		path: `${prefix}/messages/drafts`,
		action: "mail_write",
		scopes: ["drafts:create"],
		handler: handleCreateDraft,
	},
	{
		method: "PATCH",
		path: `${prefix}/messages/drafts/:id`,
		action: "mail_write",
		scopes: ["drafts:update"],
		handler: handleUpdateDraft,
	},
	{
		method: "DELETE",
		path: `${prefix}/messages/drafts/:id`,
		action: "mail_write",
		scopes: ["drafts:delete"],
		handler: handleDeleteDraft,
	},
	{
		method: "POST",
		path: `${prefix}/messages/drafts/:id/send`,
		action: "mail_write",
		scopes: ["drafts:send"],
		handler: handleSendDraft,
	},
	{
		method: "POST",
		path: `${prefix}/messages/:id/reply`,
		action: "mail_write",
		scopes: ["messages:reply"],
		handler: handleReplyToMessage,
	},
	{
		method: "POST",
		path: `${prefix}/messages/:id/forward`,
		action: "mail_write",
		scopes: ["messages:forward"],
		handler: handleForwardToMessage,
	},
	{
		method: "GET",
		path: `${prefix}/messages/:id/preview`,
		action: "mail_read",
		scopes: ["messages:read_preview"],
		handler: handleGetMessagePreview,
	},
	{
		method: "GET",
		path: `${prefix}/messages/:id/raw`,
		action: "mail_read",
		scopes: ["messages:read_raw"],
		handler: handleDownloadRawMessage,
	},
	{
		method: "GET",
		path: `${prefix}/messages/:id`,
		action: "mail_read",
		scopes: ["messages:read"],
		handler: handleGetMessage,
	},
	{
		method: "GET",
		path: `${prefix}/messages/:id/images/:imageId`,
		action: "mail_read",
		scopes: ["messages:read_images"],
		handler: handleDownloadMessageExternalImage,
	},

	{
		method: "GET",
		path: `${prefix}/threads`,
		action: "mail_read",
		scopes: ["threads:list"],
		handler: handleListThreads,
	},
	{
		method: "GET",
		path: `${prefix}/threads/:id/messages`,
		action: "mail_read",
		scopes: ["threads:read"],
		handler: handleListThreadMessages,
	},
	{
		method: "POST",
		path: `${prefix}/threads/:id/:action`,
		action: "mail_write",
		scopes: ["threads:update"],
		handler: handleThreadAction,
	},
	{
		method: "PATCH",
		path: `${prefix}/threads/:id`,
		action: "mail_write",
		scopes: ["threads:update"],
		handler: handlePatchThread,
	},
	{
		method: "GET",
		path: `${prefix}/threads/:id`,
		action: "mail_read",
		scopes: ["threads:read"],
		handler: handleGetThread,
	},

	{
		method: "POST",
		path: `${prefix}/search`,
		action: "mail_read",
		scopes: ["search:read"],
		handler: handleSearch,
	},

	{
		method: "GET",
		path: `${prefix}/attachments/:id`,
		action: "mail_read",
		scopes: ["attachments:read"],
		handler: handleDownloadAttachment,
	},
];
