import { and, eq } from "drizzle-orm";
import PostalMime from "postal-mime";

import { messages, threadMailboxes } from "../../db/schema";
import { assertOutboundMailboxAccess } from "../../lib/messages/outbound-auth";
import { assertCanSendFrom } from "../../lib/authorize-mailbox";
import { loadMailboxForSend } from "../../lib/mailbox-queries";
import { isBlackholeMailboxType } from "../../lib/mailbox-types";
import {
	assertMessageVisibleInMailbox,
	findThreadMailbox,
	onOutboundSent,
} from "../../lib/thread-mailbox";
import {
	buildForwardBodyHtml,
	buildForwardBodyText,
	buildForwardQuotedHtml,
	buildForwardQuotedText,
	forwardSubject,
} from "../../lib/messages/build-forward-content";
import {
	buildEmailSendPayload,
	buildOutboundMimeContent,
} from "../../lib/messages/build-outbound-mime";
import { buildReplyThreading } from "../../lib/messages/build-reply-threading";
import {
	completeDraftSend,
	draftSendPromoteFromDrafts,
} from "../../lib/messages/complete-draft-send";
import { canonicalizeSentMessageId } from "../../lib/messages/message-id";
import { findMessageById } from "../../lib/messages/message-queries";
import {
	loadDraftOutboundPayload,
	loadStoredAttachmentInputs,
	outboundAttachmentsToStoredInputs,
	storedInputsToOutboundAttachments,
	type OutboundAttachmentInput,
} from "../../lib/messages/outbound-attachments";
import type { OutboundContext } from "../../lib/messages/outbound-context";
import type {
	ForwardBody,
	OutboundMessageBody,
	ReplyBody,
} from "../../lib/messages/outbound-payload";
import { sendAndPersistNewMessage } from "../../lib/messages/outbound-persist";
import { formatEmailAddress } from "../../lib/addresses";
import { resolveIdentityForSend } from "../identities";
import { resolveReplyPayload } from "../../lib/messages/outbound-threading";
import { prepareOutboundMessageBody } from "../../lib/messages/prepare-email-html";
import { resolveReplyRecipients } from "../../lib/messages/resolve-reply-recipients";
import { sendEmail } from "../../lib/messages/send-email";
import { emitLog } from "../logs";
import { extractEmailsFromHeaderValue } from "../../lib/extract-emails-from-header";

export async function sendDraftMessage(
	ctx: OutboundContext,
	messageId: string,
) {
	const [draft] = await ctx.db
		.select()
		.from(messages)
		.where(
			and(
				eq(messages.id, messageId),
				eq(messages.direction, "outbound"),
				eq(messages.sendStatus, "draft"),
			),
		)
		.limit(1);

	if (!draft) {
		throw new Error("Draft not found");
	}

	await assertOutboundMailboxAccess(ctx, draft.actualMailboxId);

	const mailbox = await loadMailboxForSend(ctx.db, draft.actualMailboxId);
	if (!mailbox) {
		throw new Error("Mailbox not found or cannot send");
	}

	await assertCanSendFrom(ctx.db, mailbox.id);

	const rawPayload = await loadDraftOutboundPayload(ctx.bucket, draft);
	const payload = await prepareOutboundMessageBody(rawPayload);
	const { fromName } = await resolveIdentityForSend(
		ctx.db,
		ctx.principal,
		mailbox.id,
		payload.identityId,
	);
	const fromHeader = formatEmailAddress({
		email: mailbox.address,
		name: fromName || undefined,
	});
	const storedAttachmentInputs = await loadStoredAttachmentInputs(
		ctx.db,
		ctx.bucket,
		messageId,
	);
	const attachmentInputs = [
		...storedAttachmentInputs,
		...outboundAttachmentsToStoredInputs(payload.attachments),
	];
	const now = new Date();
	const sendPayload = buildEmailSendPayload({
		from: fromHeader,
		payload,
		inReplyTo: draft.inReplyTo,
		references: draft.references,
		attachmentInputs,
		autoGenerated: isBlackholeMailboxType(mailbox.type),
	});

	const toAddress =
		extractEmailsFromHeaderValue(draft.envelopeTo)[0] ??
		draft.envelopeTo ??
		extractEmailsFromHeaderValue(draft.to)[0] ??
		draft.to;

	let result: Awaited<ReturnType<typeof sendEmail>>;
	try {
		result = await sendEmail(ctx.email, sendPayload);
	} catch (error) {
		try {
			await emitLog(ctx.db, {
				importance: 5,
				type: "mailing",
				summary: "{from} → {to} failed",
				refs: {
					from: { kind: "mailbox", id: mailbox.id },
					to: { kind: "external-address", id: toAddress },
					message: { kind: "message", id: draft.id },
					thread: { kind: "thread", id: draft.threadId },
				},
				actorAccountId: ctx.principal.accountId,
				context: ctx.logContext ?? null,
			});
		} catch (logError) {
			console.error("Failed to emit draft send failure log:", logError);
		}
		throw error;
	}
	const rfcMessageId = canonicalizeSentMessageId(result.messageId);

	const sent = await completeDraftSend({
		db: ctx.db,
		bucket: ctx.bucket,
		draft,
		rfcMessageId,
		mimeContent: buildOutboundMimeContent({
			from: fromHeader,
			payload,
			rfcMessageId,
			inReplyTo: draft.inReplyTo,
			references: draft.references,
			autoGenerated: isBlackholeMailboxType(mailbox.type),
		}),
		attachmentInputs,
		sentAt: now,
		sentByAccountId: ctx.principal.accountId,
	});

	await onOutboundSent(ctx.db, {
		threadId: sent.threadId,
		touch: {
			subject: draft.subject,
			preview: draft.preview,
			lastMessageAt: now,
			actualMailboxId: mailbox.id,
			folder: sent.id !== draft.id ? "sent" : undefined,
			promoteFromDrafts: draftSendPromoteFromDrafts(draft, sent),
			markUnread: false,
		},
		message: sent,
	});

	try {
		await emitLog(ctx.db, {
			importance: 5,
			type: "mailing",
			summary: "{from} → {to}",
			refs: {
				from: { kind: "mailbox", id: mailbox.id },
				to: { kind: "external-address", id: toAddress },
				message: { kind: "message", id: sent.id },
				thread: { kind: "thread", id: sent.threadId },
			},
			actorAccountId: ctx.principal.accountId,
			context: ctx.logContext ?? null,
		});
	} catch (logError) {
		console.error("Failed to emit draft send log:", logError);
	}

	return sent;
}

export async function directSend(
	ctx: OutboundContext,
	mailboxId: string,
	body: OutboundMessageBody,
) {
	await assertOutboundMailboxAccess(ctx, mailboxId);
	return sendAndPersistNewMessage(
		ctx,
		mailboxId,
		body,
		{
			threadId: crypto.randomUUID(),
			inReplyTo: null,
			references: null,
			isReply: false,
		},
		"sent",
	);
}

export async function replyToMessage(
	ctx: OutboundContext,
	messageId: string,
	body: ReplyBody,
) {
	const parent = await findMessageById(ctx.db, messageId);
	if (!parent) {
		throw new Error("Message not found");
	}

	await assertOutboundMailboxAccess(ctx, body.mailboxId);

	const mailbox = await loadMailboxForSend(ctx.db, body.mailboxId);
	if (!mailbox) {
		throw new Error("Mailbox not found or cannot send");
	}

	const [threadLink] = await ctx.db
		.select({ threadId: threadMailboxes.threadId })
		.from(threadMailboxes)
		.where(
			and(
				eq(threadMailboxes.threadId, parent.threadId),
				eq(threadMailboxes.mailboxId, body.mailboxId),
			),
		)
		.limit(1);

	if (!threadLink) {
		throw new Error("Thread not found");
	}

	const replyHeaders = buildReplyThreading({
		messageId: parent.messageId,
		references: parent.references,
	});

	const resolvedRecipients = await resolveReplyRecipients(
		ctx.bucket,
		parent,
		mailbox.address,
		body.replyAll === true,
		{
			to: body.to,
			cc: body.cc,
			bcc: body.bcc,
		},
	);

	const mailboxView = await findThreadMailbox(
		ctx.db,
		parent.threadId,
		body.mailboxId,
	);
	const payload = resolveReplyPayload(body, parent, resolvedRecipients);

	return sendAndPersistNewMessage(
		ctx,
		body.mailboxId,
		payload,
		{
			threadId: parent.threadId,
			inReplyTo: replyHeaders.inReplyTo,
			references: replyHeaders.references,
			isReply: true,
		},
		mailboxView?.folder === "drafts"
			? "sent"
			: isBlackholeMailboxType(mailbox.type)
				? "sent"
				: (mailboxView?.folder ?? "inbox"),
	);
}

async function loadParentContentForForward(
	ctx: OutboundContext,
	parent: typeof messages.$inferSelect,
): Promise<{ text: string | null; html: string | null }> {
	const object = await ctx.bucket.get(parent.rawEmlKey);
	if (!object) {
		return {
			text: parent.textBody,
			html: null,
		};
	}

	const parsed = await PostalMime.parse(await object.arrayBuffer());
	return {
		text: parsed.text ?? parent.textBody,
		html: parsed.html ?? null,
	};
}

function mergeForwardAttachments(
	userAttachments: OutboundAttachmentInput[] | undefined,
	parentAttachments: OutboundAttachmentInput[],
): OutboundAttachmentInput[] | undefined {
	const merged = [...(userAttachments ?? []), ...parentAttachments];
	return merged.length > 0 ? merged : undefined;
}

export async function forwardMessage(
	ctx: OutboundContext,
	messageId: string,
	body: ForwardBody,
) {
	await assertMessageVisibleInMailbox(ctx.db, messageId, body.mailboxId);
	await assertOutboundMailboxAccess(ctx, body.mailboxId);

	const parent = await findMessageById(ctx.db, messageId);
	if (!parent) {
		throw new Error("Message not found");
	}

	const mailbox = await loadMailboxForSend(ctx.db, body.mailboxId);
	if (!mailbox) {
		throw new Error("Mailbox not found or cannot send");
	}

	const parentContent = await loadParentContentForForward(ctx, parent);
	const quotedText = buildForwardQuotedText({
		from: parent.from,
		subject: parent.subject,
		text: parentContent.text,
		sentAt: parent.sentAt,
		receivedAt: parent.receivedAt,
	});
	const quotedHtml = buildForwardQuotedHtml({
		from: parent.from,
		subject: parent.subject,
		html: parentContent.html,
		text: parentContent.text,
		sentAt: parent.sentAt,
		receivedAt: parent.receivedAt,
	});

	const text = body.includeQuotedBody
		? buildForwardBodyText(body.text, quotedText)
		: body.text;
	const html = body.includeQuotedBody
		? buildForwardBodyHtml(body.html, quotedHtml)
		: body.html;

	const parentAttachments = body.includeAttachments
		? storedInputsToOutboundAttachments(
				await loadStoredAttachmentInputs(ctx.db, ctx.bucket, messageId),
			)
		: [];

	const payload: OutboundMessageBody = {
		to: body.to,
		cc: body.cc,
		bcc: body.bcc,
		subject: body.subject ?? forwardSubject(parent.subject),
		text,
		html,
		attachments: mergeForwardAttachments(body.attachments, parentAttachments),
	};

	if (!payload.text && !payload.html) {
		throw new Error("At least one of 'text' or 'html' is required");
	}

	return sendAndPersistNewMessage(
		ctx,
		body.mailboxId,
		payload,
		{
			threadId: crypto.randomUUID(),
			inReplyTo: null,
			references: null,
			isReply: false,
		},
		"sent",
	);
}
