import { eq } from "drizzle-orm";

import { attachments, messages } from "../../db/schema";
import { authorizeMailbox } from "../../lib/auth/access";
import { loadMailboxForSend } from "../../lib/mailbox-queries";
import { isBlackholeMailboxType } from "../../lib/mailbox-types";
import { buildOutboundMimeContent } from "../../lib/messages/build-outbound-mime";
import { findDraftById, findMessageById } from "../../lib/messages/message-queries";
import { buildPreview } from "../../lib/messages/message-utils";
import {
	loadStoredAttachmentInputs,
	outboundAttachmentsToStoredInputs,
} from "../../lib/messages/outbound-attachments";
import type { OutboundContext } from "../../lib/messages/outbound-context";
import {
	formatRecipients,
	replySubject,
	type CreateDraftBody,
	type OutboundMessageBody,
} from "../../lib/messages/outbound-payload";
import { persistDraftMessage } from "../../lib/messages/outbound-pipeline";
import { resolveThreadingForCompose } from "../../lib/messages/outbound-threading";
import { resolveReplyRecipients } from "../../lib/messages/resolve-reply-recipients";
import { replaceStoredMessageContent } from "../../lib/messages/update-stored-message";
import { deleteR2Objects } from "../../lib/r2-cleanup";
import { onDraftDeleted, onDraftUpdated } from "../../lib/thread-mailbox";

export async function createDraft(
	ctx: OutboundContext,
	body: CreateDraftBody,
) {
	await authorizeMailbox(ctx.db, ctx.principal, body.mailboxId, "send");

	const { parent, threading } = await resolveThreadingForCompose(ctx.db, body);

	let to = body.to;
	let cc = body.cc;
	let bcc = body.bcc;

	if (parent && (!to || to.length === 0)) {
		const mailbox = await loadMailboxForSend(ctx.db, body.mailboxId);
		if (!mailbox) {
			throw new Error("Mailbox not found or cannot send");
		}

		const resolved = await resolveReplyRecipients(
			ctx.bucket,
			parent,
			mailbox.address,
			body.replyAll === true,
			{ to, cc, bcc },
		);
		to = resolved.to;
		cc = resolved.cc ?? cc;
		bcc = resolved.bcc ?? bcc;
	}

	const payload: OutboundMessageBody = {
		to: to ?? [],
		cc,
		bcc,
		subject: body.subject || (parent ? replySubject(parent.subject) : ""),
		text: body.text,
		html: body.html,
		attachments: body.attachments,
	};

	return persistDraftMessage(ctx, body.mailboxId, payload, threading);
}

export async function getDraft(ctx: OutboundContext, messageId: string) {
	const draft = await findDraftById(ctx.db, messageId);
	if (!draft) {
		throw new Error("Draft not found");
	}

	await authorizeMailbox(ctx.db, ctx.principal, draft.actualMailboxId, "read");
	return draft;
}

export async function updateDraft(
	ctx: OutboundContext,
	messageId: string,
	body: OutboundMessageBody,
) {
	const draft = await findDraftById(ctx.db, messageId);
	if (!draft) {
		throw new Error("Draft not found");
	}

	const mailboxId = draft.actualMailboxId;
	await authorizeMailbox(ctx.db, ctx.principal, mailboxId, "send");
	const mailbox = await loadMailboxForSend(ctx.db, mailboxId);
	if (!mailbox) {
		throw new Error("Mailbox not found or cannot send");
	}

	const recipients = formatRecipients(body);
	const preview = buildPreview(body.text ?? null);
	const attachmentInputs =
		body.attachments !== undefined
			? outboundAttachmentsToStoredInputs(body.attachments)
			: await loadStoredAttachmentInputs(ctx.db, ctx.bucket, messageId);
	const now = new Date();

	await replaceStoredMessageContent(
		ctx.db,
		ctx.bucket,
		messageId,
		buildOutboundMimeContent({
			from: mailbox.address,
			payload: body,
			rfcMessageId: draft.messageId,
			inReplyTo: draft.inReplyTo,
			references: draft.references,
			autoGenerated: isBlackholeMailboxType(mailbox.type),
		}),
		attachmentInputs,
		{
			to: recipients.to,
			cc: recipients.cc,
			bcc: recipients.bcc,
			envelopeTo: recipients.envelopeTo,
			subject: body.subject,
			textBody: body.text ?? null,
			preview,
			hasHtml: Boolean(body.html),
			receivedAt: now,
		},
	);

	await onDraftUpdated(ctx.db, {
		threadId: draft.threadId,
		mailboxId,
		touch: {
			subject: body.subject,
			preview,
			lastMessageAt: now,
		},
	});

	const updated = await findMessageById(ctx.db, messageId);
	if (!updated) {
		throw new Error("Updated draft not found");
	}

	return updated;
}

export async function deleteDraft(
	ctx: OutboundContext,
	messageId: string,
): Promise<void> {
	const draft = await findDraftById(ctx.db, messageId);
	if (!draft) {
		throw new Error("Draft not found");
	}

	await authorizeMailbox(ctx.db, ctx.principal, draft.actualMailboxId, "read");

	const storedAttachments = await ctx.db
		.select({ storageKey: attachments.storageKey })
		.from(attachments)
		.where(eq(attachments.messageId, messageId));

	const threadId = draft.threadId;
	await ctx.db.delete(attachments).where(eq(attachments.messageId, messageId));
	await ctx.db.delete(messages).where(eq(messages.id, messageId));
	await onDraftDeleted(ctx.db, { threadId });
	await deleteR2Objects(ctx.bucket, [
		draft.rawEmlKey,
		...storedAttachments.map((attachment) => attachment.storageKey),
	]);
}
