import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

import {
	apiProxyTarget,
	type Conf,
	productionWebOrigin,
} from "./config.js";
import type { RepoPaths } from "./paths.js";
import {
	CORE_WRANGLER_HEADER,
	coreWrangler,
	GATE_WRANGLER_HEADER,
	gateWrangler,
	toJsonc,
} from "./templates.js";

export function materialize(conf: Conf, paths: RepoPaths): void {
	writeFile(paths.coreWrangler, toJsonc(CORE_WRANGLER_HEADER, coreWrangler(conf)));
	writeFile(paths.gateWrangler, toJsonc(GATE_WRANGLER_HEADER, gateWrangler(conf)));
	writeFile(paths.coreEnv, coreEnvFile(conf));
	writeFile(paths.webEnv, webEnvFile(conf));
}

export function coreEnvFile(conf: Conf): string {
	return [
		"# Generated by `flaremail sync`. Edit flaremail.conf.jsonc instead.",
		"",
		`DATABASE_URL=${dotenvValue(conf.database.url)}`,
		`SESSION_SECRET=${dotenvValue(conf.secrets.SESSION_SECRET)}`,
		"# Local wrangler/gate origin. Production WEB_ORIGIN is in wrangler.jsonc.",
		"WEB_ORIGIN=http://localhost:8787",
		`OIDC_SIGNING_JWK=${dotenvValue(conf.secrets.OIDC_SIGNING_JWK)}`,
		"",
	].join("\n");
}

export function webEnvFile(conf: Conf): string {
	return [
		"# Generated by `flaremail sync`. Edit flaremail.conf.jsonc instead.",
		"",
		"API_URL=/api/v1",
		`API_PROXY_TARGET=${dotenvValue(apiProxyTarget(conf) || productionWebOrigin(conf))}`,
		"",
	].join("\n");
}

function dotenvValue(value: string): string {
	if (value === "") return "";
	if (/^[A-Za-z0-9_./:@%+=-]*$/.test(value) && !value.includes(" ")) {
		return value;
	}
	return `'${value.replace(/'/g, "'\\''")}'`;
}

function writeFile(path: string, contents: string): void {
	mkdirSync(dirname(path), { recursive: true });
	writeFileSync(path, contents, { encoding: "utf8" });
}
