import type { Conf } from "./config.js";
import { gateHostname, productionWebOrigin } from "./config.js";

const SCHEMA = "../../node_modules/wrangler/config-schema.json";

export const REQUIRED_SECRETS = ["SESSION_SECRET", "OIDC_SIGNING_JWK"] as const;

export function coreWrangler(conf: Conf): unknown {
	const hyperdriveId =
		conf.database.hyperdrive.id.trim() || "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
	return {
		$schema: SCHEMA,
		name: conf.core.workerName,
		main: "src/index.ts",
		compatibility_date: "2026-06-29",
		workers_dev: false,
		preview_urls: false,
		observability: { enabled: true },
		upload_source_maps: true,
		compatibility_flags: ["nodejs_compat"],
		hyperdrive: [{ binding: "HYPERDRIVE", id: hyperdriveId }],
		r2_buckets: [{ binding: "BUCKET", bucket_name: conf.r2.bucketName }],
		secrets: { required: [...REQUIRED_SECRETS] },
		vars: { WEB_ORIGIN: productionWebOrigin(conf) },
		send_email: [{ name: "EMAIL", remote: true }],
		triggers: { crons: ["*/2 * * * *"] },
		ratelimits: [
			rateLimit("RATE_LIMIT_GLOBAL", "1001", 120, 60),
			rateLimit("RATE_LIMIT_AUTH", "1002", 30, 60),
			rateLimit("RATE_LIMIT_AUTH_FAILURE", "1003", 10, 60),
			rateLimit("RATE_LIMIT_INVITE", "1004", 10, 60),
		],
	};
}

export function gateWrangler(conf: Conf): unknown {
	const hostname = gateHostname(conf);
	return {
		$schema: SCHEMA,
		name: conf.gate.workerName,
		main: "src/index.ts",
		compatibility_date: "2026-06-29",
		observability: { enabled: true },
		upload_source_maps: true,
		assets: {
			directory: "../web/dist",
			not_found_handling: "single-page-application",
			run_worker_first: ["/api/*", "/health"],
		},
		services: [{ binding: "CORE", service: conf.core.workerName }],
		routes: [{ pattern: hostname, custom_domain: true }],
	};
}

function rateLimit(name: string, namespace_id: string, limit: number, period: number) {
	return { name, namespace_id, simple: { limit, period } };
}

export function toJsonc(header: string, value: unknown): string {
	return `${header}\n${JSON.stringify(value, null, "\t")}\n`;
}

export const CORE_WRANGLER_HEADER = `/**
 * Generated by \`flaremail sync\`. Do not edit — change flaremail.conf.jsonc instead.
 * https://developers.cloudflare.com/workers/wrangler/configuration/
 */`;

export const GATE_WRANGLER_HEADER = `/**
 * Generated by \`flaremail sync\`. Do not edit — change flaremail.conf.jsonc instead.
 * Public edge: SPA assets from apps/web + /api/* proxy to core.
 */`;
